### PR TITLE
Development wheel

### PR DESCRIPTION
**Pull request by thewtex**

### CODE REVIEW

**Comment by thewtex** [comment]
@hjmjohnson @aylward @dzenanz WIP

**Comment by hjmjohnson** [comment]
Did all the other instructions work as described?  Or is this just the first in a sequence of proposed changes?

**Comment by thewtex** [comment]
> Did all the other instructions work as described? Or is this just the first in a sequence of proposed changes?

The other instructions need improvement. This is just the first in a sequence of proposed changes.

**Review by hjmjohnson — APPROVED** [review]

**Comment by thewtex** [comment]
@hjmjohnson added instructions on how to build against a custom version of ITK.

**Comment by dzenanz** [comment]
I think @aylward was interested in this at some point in time.

**Pull request merged**
