### PR TITLE
COMP: Update dockcross images for CPython 3.11.0

### PR DESCRIPTION
**Pull request by thewtex**

### CODE REVIEW

**Comment by thewtex** [comment]
@tbirdso needs to be tested

**Review by dzenanz — APPROVED** [review]

**Comment by tbirdso** [comment]
Hi @thewtex , thanks for working on this. I am still seeing pre-release Python 3.11.0b3 in the updated image. I am not sure the update addressed the issue?

```
> docker run --rm dockcross/manylinux_2_28-x64:20221103-57a27d5 > /tmp/dockcross-manylinux-x64
> /tmp/dockcross-manylinux-x64 bash
>>>  /opt/python/cp311-cp311/bin/python --version
Python 3.11.0b3
```

**Comment by thewtex** [comment]
@tbirdso interesting, here is what I get:

```
❯  docker run --rm dockcross/manylinux_2_28-x64:20221103-57a27d5 > /tmp/dockcross-manylinux-x64
❯ chmod +x /tmp/dockcross-manylinux-x64
❯ /tmp/dockcross-manylinux-x64 bash
[matt:/work] $ /opt/python/cp311-cp311/bin/python --version
Python 3.11.0
```

**Comment by thewtex** [comment]
@tbirdso please try:

```
docker pull dockcross/manylinux_2_28-x64:latest
```

and  try again.

This is the default image name in the generated dockcross script (though it should be the tagged version).

**Comment by thewtex** [comment]
Addressed in dockcross here: https://github.com/dockcross/dockcross/pull/738

**Comment by tbirdso** [comment]
Hi @thewtex , thanks for taking a look. I'm not sure I understand what the issue and fix were here. Was this an issue affecting only `dockcross/manylinux_2_28-x64:latest`? If there was an issue with the `dockcross/manylinux_2_28-x64:20221103-57a27d5` image then why are we seeing different results when we pull the same image?

**Comment by thewtex** [comment]
> ❯ chmod +x /tmp/dockcross-manylinux-x64

@tbirdso in `/tmp/dockcross-manylinux-x64` line 3, it is using `dockcross/manylinux_2_28-x64:latest`, which will be fixed by https://github.com/dockcross/dockcross/pull/738 so that it has the explicit tag instead of `latest`.

Docker will download a `latest` image the first time it is used, but it does not download after it is available locally. So, if you have the image locally, you need to explicitly pull to get the update.

**Review by tbirdso — APPROVED** [review]
Tested and verified that after updating the `latest` cache the new image shows `Python 3.11`

**Comment by tbirdso** [comment]
Hi @thewtex , please find the updated archive from `blaster` here: https://drive.google.com/file/d/1N0Hr7SKzyfy7HAqFjhs41KmOJMIAygHd/view?usp=share_link

**Comment by thewtex** [comment]
Will follow up with another bump after dockcross 738 is in.

**Pull request merged**
