### PR TITLE
Fix extraction of itk group name

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Comment by jcfr** [comment]
The following warning is still reported:

```
CMake Warning (dev) at cmake/ITKPythonPackage.cmake:86 (message):
  Variable ITK_MODULE_ITKKWIML_GROUP is not defined
Call Stack (most recent call first):
  CMakeLists.txt:532 (ipp_is_module_python_wrapped)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

**Comment by jcfr** [comment]
The KWIML module has been removed in InsightSoftwareConsortium/ITK@3a4fbd65a78101a12119bd9fd4c369b9c2e3f4bd

**Comment by jcfr** [comment]
The KWIML error was unrelated and were due to an older ITK build tree I was using.

**Review by thewtex — APPROVED** [review]
:1st_place_medal: @jcfr awesome, thank you!

**Pull request merged**
